export  const fakedata=[
  {id:1,question:"What is JavaScript?",Iname:"Soumitya Chauhan",category:"javascript",difficulty:"not specified"},
  {id:2,question:" hosting",Iname:"Soumitya Chauhan",category:"javascript",difficulty:"not specified"},
  {id:3,question:"what is higher Order function?",Iname:"Soumitya Chauhan",category:"javascript",difficulty:"not specified"},
  {id:4,question:"event loop ?",Iname:"Soumitya Chauhan",category:"javascript",difficulty:"not specified"},
  {id:5,question:"splice() vs Slice()",Iname:"Soumitya Chauhan",category:"javascript",difficulty:"not specified"},
  {id:6,question:"what is NaN?",Iname:"Soumitya Chauhan",category:"javascript",difficulty:"not specified"},
  {id:7,question:"Undefined and Null",Iname:"Soumitya Chauhan",category:"javascript",difficulty:"not specified"},
  {id:8,question:"anonymous function",Iname:"Soumitya Chauhan",category:"javascript",difficulty:"not specified"},
  {id:9,question:"what is teranary operator ?",Iname:"Soumitya Chauhan",category:"javascript",difficulty:"not specified"},
  {id:10,question:"what is callback?",Iname:"Soumitya Chauhan",category:"javascript",difficulty:"not specified"},
  {id:11,question:"What is the difference between Local storage & Session storage?",Iname:"Soumitya Chauhan",category:"javascript",difficulty:"not specified"},
  {id:12,question:"Define closure.",Iname:"Soumitya Chauhan",category:"javascript",difficulty:"not specified"},
  {id:13,question:"How can you create an object in JavaScript?",Iname:"Soumitya Chauhan",category:"javascript",difficulty:"not specified"},
  {id:14,question:"What is Data Type?",Iname:"Soumitya Chauhan",category:"javascript",difficulty:"not specified"},
  {id:15,question:"let and const and var",Iname:"Soumitya Chauhan",category:"javascript",difficulty:"not specified"},
  {id:16,question:"console.log('5'+5);",Iname:"Soumitya Chauhan",category:"javascript",difficulty:"not specified"},
  {id:17,question:"console.log('5'-5)",Iname:"Soumitya Chauhan",category:"javascript",difficulty:"not specified"},
  {id:18,question:"Difference between “==” and “===” operators.",Iname:"Soumitya Chauhan",category:"javascript",difficulty:"not specified"},
]